flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
    title = StringField('Title',
                        validators=[DataRequired()])
    content = TextAreaField('Content',
                            validators=[DataRequired()])
    submit = SubmitField('Post')

flaskblog/main/routes.py
from flask import Blueprint
from flaskblog.models import Post
from flask import render_template, request

main = Blueprint('main', __name__)

@main.route("/") # This allows us to tell Flask what URL to trigger. Returns the information shown on the page
@main.route("/home") # Adding another decorator for same function
def home():
    page = request.args.get('page', 1, type=int) # This requests the 'page' part of the url, and defaults it to 1
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=3) # Order the posts by descending date, and 3 posts per page
    return render_template('home.html', posts=posts)

@main.route("/about") # This allows us to tell Flask what URL to trigger. Returns the information shown on the page
def about():
    return render_template('about.html', title='About')

flaskblog/posts/routes.py
from flask import Blueprint
from flaskblog.models import Post
from flask import abort, render_template, request, url_for, flash, redirect
from flaskblog.posts.forms import PostForm
from flaskblog import db
from flask_login import current_user, login_required

posts = Blueprint('posts', __name__)

@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash("Your post has been created!", 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post', 
                           form=form, legend='New Post')

@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id) # Grabs specific post form database
    return render_template('post.html', title=post.title, post=post)

@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id) 
    if post.author != current_user: # Only the current user can update their post
        abort(403) # 403 = forbidden route
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit() # Don't need to add, as post is already in database
        flash("your post has been updated!", 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post', 
                           form=form, legend='Update Post')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id) 
    if post.author != current_user: # Only the current user can update their post
        abort(403) # 403 = forbidden route
    db.session.delete(post)
    db.session.commit()
    flash("Your post has been deleted!", 'success')
    return redirect(url_for('main.home'))

flaskblog/users/routes.py
from flask import Blueprint
from flaskblog.models import User, Post
from flask import render_template, request, url_for, flash, redirect
from flaskblog.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from flaskblog.users.utils import save_picture, send_reset_email
from flaskblog import db, bcrypt
from flask_login import login_user, current_user, logout_user, login_required

users = Blueprint('users', __name__) # Initialise an instance of Blueprint, pass in name of the blueprint 

@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Your account has been created. You are now able to log in', 'success') # In flask-WTF, the input data in StringFields is labelled as 'data'. Flash function will show something on the screen once
        return redirect(url_for('main.home'))
    return render_template('register.html', title='Register', form=form)

@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data): # If user exists and password is valid (checking db password vs form password)
            login_user(user, remember=form.remember.data)
            flash("Login successful!", 'success')
            return redirect(url_for('main.home'))
        else:
            flash("Login unsuccessful! Please check email and password", 'danger')
    return render_template('login.html', title='Login', form=form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data) # Takes the picture entered by the user and gets the file, then updates their picture
            current_user.image_file = picture_file
        current_user.username = form.username.data # Updates the database with the form entry
        current_user.email = form.email.data # Updates the database with the form entry
        db.session.commit()
        flash(f'Your account has been updated', 'success')
        return redirect (url_for('users.account')) # Important to have redirect (POST GET REDIRECT PATTERN = confirm resubmission, don't want this)
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)


@users.route("/user/<string:username>") # Means the string part after the 'user' in the url will be captured as the username
def user_posts(username):
    page = request.args.get('page', 1, type=int) # This requests the 'page' part of the url, and defaults it to 1
    user = User.query.filter_by(username=username).first_or_404() # If username isn't found in database, returns 404. Otherwise, makes that user 'user'
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=3) # Retrieve the posts created by that username using 'author'. Order the posts by descending date, and 3 posts per page
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first() # Grabs first user that has the email entered in the Request form
        send_reset_email(user)
        flash("An email has been sent with instructions on how to reset your password.", 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)

@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token) # Gets the token from this method in the User class
    if user is None: # If no user_id is returned i.e. token is expired or wrong
        flash("That is an invalid or expired token", 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(f'Your password has been updated! You are now able to log in.', 'success') # In flask-WTF, the input data in StringFields is labelled as 'data'. Flash function will show something on the screen once
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form) # Renders template to reset password (if token is valid)

flaskblog/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}
    

flaskblog/templates/account.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
        <h2 class="account-heading">{{ current_user.username }}</h2>
        <p class="text-secondary">{{ current_user.email }}</p>
        </div>
    </div>
    <div class="content-section">
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }} <!--This adds a CSRF token to our registration form - uses secret key-->
            <fieldset class = "form-group"> <!-- Space for creating divs for the different parts of the form. They are all related form controls-->
                <legend class="border-bottom mb-4">Account Info</legend> <!-- Legend element gives a caption for the fieldset-->
                <div class="form-group"> 
                    {{ form.username.label(class="form-control-label")}} <!-- Prints out label from username field, gives class which is just bootstrap stuff, makes it look nicer-->
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid")}}    
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg")}}
                    {% endif %}
                </div>
                <div class="form-group"> 
                    {{ form.email.label(class="form-control-label")}} 
                    {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid")}}    
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg")}}
                {% endif %}
                </div>
                <div class="form-group"> 
                    {{ form.picture.label() }}</br>
                    {{ form.picture(class="form-control-file") }}</br>
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group"> 
                {{ form.submit(class="btn btn-outline-info")}} 
            </div>
        </form>
    </div>
</div>
{% endblock content %}

flaskblog/templates/create_post.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class = "form-group"> 
            <legend class="border-bottom mb-4">{{ legend }}</legend> 
            <div class="form-group"> 
                {{ form.title.label(class="form-control-label")}} 
                {% if form.title.errors %}
                {{ form.title(class="form-control form-control-lg is-invalid")}}    
                <div class="invalid-feedback">
                    {% for error in form.title.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.title(class="form-control form-control-lg")}}
            {% endif %}
            </div>
            <div class="form-group"> 
                {{ form.content.label(class="form-control-label")}} 
                {% if form.content.errors %}
                {{ form.content(class="form-control form-control-lg is-invalid")}}    
                <div class="invalid-feedback">
                    {% for error in form.content.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.content(class="form-control form-control-lg")}}
            {% endif %}
            </div>
            <div class="form-group"> 
                {{ form.submit(class="btn btn-outline-info" )}} 
            </div>
        </fieldset>
    </form>
</div>
{% endblock content %}

flaskblog/templates/home.html
{% extends "layout.html" %}
{% block content %}
    {% for post in posts.items %}
    <article class="media content-section">
        <div class="media-body">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
          </div>
          <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
          <p class="article-content">{{ post.content }}</p>
        </div>
    </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=1) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="'btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="'btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}

flaskblog/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>A Blog by Terrell - {{title}}</title>
    {% else %}
        <title>A Blog by Terrell</title>
    {% endif %}
</head>

<body>
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
            <a class="navbar-brand mr-4" href="/">A Blog by Terrell</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                  {% if current_user.is_authenticated %}
                  <a class="nav-item nav-link" href= "{{ url_for('posts.new_post') }}">New Post</a>
                    <a class="nav-item nav-link" href= "{{ url_for('users.account') }}">Account</a>
                    <a class="nav-item nav-link" href= "{{ url_for('users.logout') }}">Logout</a>
                  {% else %}
                    <a class="nav-item nav-link" href= "{{ url_for('users.login') }}">Login</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                  {% endif %}
                </div>
            </div>
            </div>
        </nav>
    </header>
    <main role="main" class="container">
        <div class="row">
          <div class="col-md-8">
            {% with messages = get_flashed_messages(with_categories=true) %}
              {% if messages %}
                {% for category, message in messages %}
                  <div class="alert alert-{{ category }}">
                    {{ message }}
                  </div>
                {% endfor %}
              {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
          </div>
          <div class="col-md-4">
            <div class="content-section">
              <h3>Our Sidebar</h3>
              <p class='text-muted'>You can put any information here you'd like.
                <ul class="list-group">
                  <li class="list-group-item list-group-item-light">Latest Posts</li>
                  <li class="list-group-item list-group-item-light">Announcements</li>
                  <li class="list-group-item list-group-item-light">Calendars</li>
                  <li class="list-group-item list-group-item-light">etc</li>
                </ul>
              </p>
            </div>
          </div>
        </div>
    </main>    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</body>
</html>

flaskblog/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }} <!--This adds a CSRF token to our registration form - uses secret key-->
            <fieldset class = "form-group"> <!-- Space for creating divs for the different parts of the form. They are all related form controls-->
                <legend class="border-bottom mb-4">Log In</legend> <!-- Legend element gives a caption for the fieldset-->
                <div class="form-group"> 
                    {{ form.email.label(class="form-control-label")}} 
                    {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid")}}    
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg")}}
                {% endif %}
                </div>
                <div class="form-group"> 
                    {{ form.password.label(class="form-control-label")}} 
                    {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid")}}    
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control form-control-lg")}}
                {% endif %}
                </div>
                <div class="form-check"> <!-- If user wants to remember the password -->
                    {{ form.remember (class="form-check-input") }}
                    {{ form.remember.label (class="form-check-label") }}
                </div>
                <div class="form-group"> 
                    {{ form.submit(class="btn btn-outline-info" )}} 
                    <small class="text-muted ml-2">
                        <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                    </small>
                </div>
            </fieldset>
    
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account?<a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

flaskblog/templates/post.html
{% extends "layout.html" %}
{% block content %}
    <article class="media content-section">
        <div class="media-body">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            {% if post.author == current_user %}
                <div>
                    <a class="btn btn-secondary btn-sm mt-1 mb-1" href = "{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
                    <button type="button" class="btn btn-danger btn-sm m-1" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete</button>
                </div>
            {% endif %}
          </div>
          <h2 class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</h2>
          <p class="article-content">{{ post.content }}</p>
        </div>
    </article>
    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
            <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-footer">
                <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
        </div>
    </div>
{% endblock content %}

flaskblog/templates/register.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }} <!--This adds a CSRF token to our registration form - uses secret key-->
            <fieldset class = "form-group"> <!-- Space for creating divs for the different parts of the form. They are all related form controls-->
                <legend class="border-bottom mb-4">Join today!</legend> <!-- Legend element gives a caption for the fieldset-->
                <div class="form-group"> 
                    {{ form.username.label(class="form-control-label")}} <!-- Prints out label from username field, gives class which is just bootstrap stuff, makes it look nicer-->
                    
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid")}}    
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg")}}
                    {% endif %}
                </div>
                <div class="form-group"> 
                    {{ form.email.label(class="form-control-label")}} 
                    {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid")}}    
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg")}}
                {% endif %}
                </div>
                <div class="form-group"> 
                    {{ form.password.label(class="form-control-label")}} 
                    {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid")}}    
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control form-control-lg")}}
                {% endif %}
                </div>
                <div class="form-group"> 
                    {{ form.confirm_password.label(class="form-control-label")}} 
                    {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class="form-control form-control-lg is-invalid")}}    
                    <div class="invalid-feedback">
                        {% for error in form.confirm_password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.confirm_password(class="form-control form-control-lg")}}
                {% endif %}
                </div>
            </fieldset>
            <div class="form-group"> 
                {{ form.submit(class="btn btn-outline-info")}} 
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account?<a class="ml-2" href="{{ url_for('users.login') }}">Sign In</a>
        </small>
    </div>
{% endblock content %}

flaskblog/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }} <!--This adds a CSRF token to our registration form - uses secret key-->
            <fieldset class = "form-group"> <!-- Space for creating divs for the different parts of the form. They are all related form controls-->
                <legend class="border-bottom mb-4">Reset Password</legend> <!-- Legend element gives a caption for the fieldset-->
                <div class="form-group"> 
                    {{ form.email.label(class="form-control-label")}} 
                    {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid")}}    
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg")}}
                {% endif %}
                </div>
                <div class="form-group"> 
                    {{ form.submit(class="btn btn-outline-info" )}} 
                </div>
            </fieldset>
        </form>
    </div>
{% endblock content %}

flaskblog/templates/user_posts.html
{% extends "layout.html" %}
{% block content %}

<h1 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h1>
    {% for post in posts.items %}
    <article class="media content-section">
        <div class="media-body">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
          </div>
          <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
          <p class="article-content">{{ post.content }}</p>
        </div>
    </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=1) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="'btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a> <!--Generates the url, defining the username and page parameters--> 
        {% else %}
          <a class="'btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}